#!/bin/bash

spec="$DETOUL_TMP/spec"
rm -f "$spec"

if [ "$(echo "$DETOUL_BRANCH" | grep -P "^detoul-.+" | wc -l)" == "1" ]; then
  branches="$(echo "$DETOUL_BRANCH" | sed -e 's/-\?detoul-/ /g')"
  for branch in $branches; do
    echo "take $branch" >> "$spec"
  done
else
  spec_hash="$(git ls-tree detoul-spec | grep "\s$DETOUL_BRANCH$" | xargs echo | cut -d' ' -f3)"
  if [ "$spec_hash" == "" ]; then
    echo -e "\e[31mBranch specification file not found.\e[0m"
    exit 1
  fi
  git show "$spec_hash" > "$spec"
fi

if [ "$1" == "filtered" ]; then
  content="$(cat "$spec")"
  echo "$content" | sed -e "s/\#.*$//g" | grep -vi "^$" > "$spec"
fi
