#!/bin/bash

spec="$DETOUL_TMP/spec"
rm -f "$spec"

#if (echo "$DETOUL_BRANCH" | grep -q -P "^detoul-.+"); then
#  branches="$(echo "$DETOUL_BRANCH" | sed -e 's/-\?detoul-/ /g')"
#  for branch in $branches; do
#    echo "take $branch" >> "$spec"
#  done
#else
  spec_hash="$(git ls-tree detoul-spec | grep "\s$DETOUL_BRANCH$" | xargs echo | cut -d' ' -f3)"
  if [ "$spec_hash" == "" ]; then
    if [ "${1/archived}" != "$1" ]; then
      spec_hash="$(git ls-tree detoul-spec -- .archive/ | grep "\s.archive/$DETOUL_BRANCH$" | xargs echo | cut -d' ' -f3)"
    fi
    if [ "$spec_hash" == "" ]; then
      echo -e "\033[31mBranch specification file not found.\033[0m"
      exit 1
    fi
  fi
  git show "$spec_hash" > "$spec"
#fi

if [ "${1/filtered}" != "$1" ]; then
  content="$(cat "$spec")"
  echo "$content" | sed -e "s/\#.*$//g" | grep -vi "^$" > "$spec"
fi
